name: "Update Changelog"
on:
  push:
    branches:
      - master

jobs:
  update-changelog:
    runs-on: ubuntu-latest
    if: github.repository == 'SweptWasTaken/ss14-changelog-test'
    steps:
    - name: Get The Script
      run: |
        wget "https://raw.githubusercontent.com/${{ github.repository }}/master/.github/changelog.py"
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pygithub pytz
    - name: Update Changelog
      run: |
        python changelog.py
      env:
        REPO: ${{ github.repository }}
        TOKEN: ${{ secrets.GITHUB_TOKEN }}
        CHANGELOG_PATH: strings/changelog.yml
        GIT_EMAIL: "sweptwastaken@protonmail.com"
        GIT_NAME: "SweptWasTaken"
